DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS protocols;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
